### ISSUE TITLE
Printed default config is invalid 

### ISSUE THREAD

**Issue by Hipska** [go-graphite/graphite-clickhouse#235]
When running `graphite-clickhouse -config-print-default` to generate a default config, the produced output is not valid to use:
```
2023/06/08 16:00:18 (57, 2): Can't convert false(bool) to time.Duration
```

It is about this section where `extended-stats` is not part of `[metrics.find-ranges]` but should be part of `[metrics]`.
```toml
[metrics]
 # graphite relay address
 metric-endpoint = ""
 # statsd server address
 statsd-endpoint = ""
 # graphite metrics send interval
 metric-interval = "0s"
 # graphite metrics send timeout
 metric-timeout = "0s"
 # graphite metrics prefix
 metric-prefix = ""
 # Request historgram buckets widths
 request-buckets = []
 # Request historgram buckets labels
 request-labels = []

 # Additional separate stats for until-from ranges
 [metrics.ranges]

 # Additional separate stats for until-from find ranges
 [metrics.find-ranges]
 # Extended metrics
 extended-stat = false
```
